# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROP', 'Предложение новости'), ('PUB', 'Опубликование новости')], default='PROP', max_length=4)),
                ('amount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.CharField(blank=True, max_length=3000, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Admin')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.News')),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('vk_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.VKUser'),
        ),
        migrations.AddField(
            model_name='income',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.News'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='vk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.VKUser'),
        ),
        migrations.AddField(
            model_name='adminreview',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.News'),
        ),
        migrations.AddField(
            model_name='admin',
            name='vk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.VKUser'),
        ),
    ]
